name: valotas.com

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run lint --workspaces --if-present
      - run: npm run build
      - run: npm run test

      # Upload build artifacts
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          name: valotas-static-website
          path: packages/web/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy-group
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      # Download build artifacts
      - uses: actions/download-artifact@v3
        with:
          name: valotas-static-website
          path: packages/web/dist

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
